### ISSUE TITLE
Petra File Cipher GS 암복호화 현황판 및 암복호화 결과 수치 계산식 확인 요청

### ISSUE THREAD

**Issue by hyewonLeeSinsiway** [sinsiway-official/petra_file_cipher_gs#8]
![Screenshot_12](https://user-images.githubusercontent.com/62870767/197471373-610bb3d2-0235-4903-9750-3566c8b87772.png)
현황판의 수치 어떻게 카운팅 하는지 기준 모호함

![Screenshot_13](https://user-images.githubusercontent.com/62870767/197471386-5053e5c2-e6a4-4238-b6c4-ccc988602650.png)
![Screenshot_15](https://user-images.githubusercontent.com/62870767/197471400-1488bd80-0717-4867-8f8e-9e6d22f42148.png)
![Screenshot_14](https://user-images.githubusercontent.com/62870767/197471406-723cb4cb-99f5-4af7-aefc-26c7368bf33b.png)
실제 암호화 명시한 내용은 모두 완료됐는데 완료가 50%로 나옴(100% 으로 나와야함)
수치 계산식 확인 필요

**Comment by hyewonLeeSinsiway** [comment]
petra_2022_10_24.war 으로 확인한 결과 마이너스 값으로 나옵니다. 확인 바랍니다. 


![Screenshot_16](https://user-images.githubusercontent.com/62870767/197485405-4f10273d-5622-4e65-9030-cd021c57b9ac.png)
![Screenshot_17](https://user-images.githubusercontent.com/62870767/197485413-1aae142e-c0d1-48ac-80b5-07a50f3a0232.png)

**Comment by hyewonLeeSinsiway** [comment]
이슈 상황 재현 안되고 있어 개선 지연 중.
테스트 환경 마련되면 다시 말씀드리겠습니다.

**Comment by poorants** [comment]
대시 보드는 데이터 수집에 사용되는 값이 부정확하여 전면 수정 예정입니다. 
기존 대시 보드 관련 이슈는 일단 보류 혹은 종료 부탁합니다.
